name: consensus_docking
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - pandas
  - rdkit
  - openbabel
  - prody
  - opencadd
  - biopython
  - mdanalysis
  - biopandas
  - pip
  - pip:
    - redo
